### ISSUE TITLE
error in update.json

### ISSUE THREAD

**Issue by IzzySoft** [Jefferderp/Magisk-KeyboardRemaps#1]
Your `update.json` does not match your module. Could you please adjust?

```json
{
  "version": "v1.0",
  "versionCode": 10,
  "zipUrl": "https://github.com/Jefferderp/Magisk-KeyboardRemaps/releases/download/v1.0/Magisk-KeyboardRemaps-v1.zip",
  "changelog": "https://github.com/Jefferderp/Magisk-KeyboardRemaps/raw/master/changelog.md"
}
```

Funnily your changelog reaches up to v2.0, but there are no matching releases – and the release date of v1.0 is newer than that of the v2.0 mentioned in the changelog. Further your `module.prop` states `version: 1` and `versionCode: 1`, so versioning seems to be pretty much out of sync…

**Comment by Jefferderp** [comment]
I threw the module together in an afternoon, just for my own purposes, and wasn't concerned with the version number. However I did notice that the update URL was not working.

I've just corrected both, and thanks for your input.

**Comment by IzzySoft** [comment]
Thanks for your swift action – looks fine now and works!

**Comment by IzzySoft** [comment]
Could you please also update `module.prop` so it reflects the `versionCode` communicated by `update.json`? Currently, `update.json` says `versionCode: 10` would be available, while `module.prop` (also the one included in the ZIP) still have `versionCode: 1`, which causes an "eternal update cycle" as on each check there seems to be an update available.

Thanks in advance!

**Comment by Jefferderp** [comment]
Thanks, I noticed the persistent update prompt but hadn't investigated.

I opted to specify `version` as `v1.0` and revert `versionCode` to `1` everwhere. I've also uploaded a corrected release package.

Thanks for your help!

**Comment by IzzySoft** [comment]
Umpf; not the best idea to revert `versionCode` to `1` IMHO – one should never decrease that. I had meanwhile mitigated by updating it to `10` here in the local copy – so now users have to wait 10 more versions before they'll see any update again (and besides, as there were 4 releases before that, so `1` looks a bit strange anyway :wink:). Maybe you could make that consistently `10` for now, and with future releases remember to increase it consistently as well?

**Comment by Jefferderp** [comment]
Thanks, I wasn't aware that this module had been mirrored in any repo. I've unified `versionCode` to `10` everywhere. I hope that resolves things :). I'm aware of best practices re: versioning, but I didn't anticipate this module receiving any attention.

Thanks again.

**Comment by IzzySoft** [comment]
Thanks a lot!!! :hugs:

Yeah, my repo is pretty young still – it just went "open beta" a week ago. Only F/LOSS modules are allowed in. Back-end and front-end are still WIP: a week ago it got "stable enough" to be usable, and bit by bit the gaps are closed. 50 modules are listed by now. If you miss one, I'm open to suggestions! Some are still on my list to be added but have some issues preventing them from such (usually with possibilities for automated updates; next to `update.json`, for about a week there are now 2 additional methods, but still some "special setups" don't fit any of them…
